[package]
name = "speedwizard"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.9.6", package = "gtk4" }
adw = { version = "0.7.1", package = "libadwaita" }
glib = "0.18"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
gio = "0.20.9"
lazy_static = "1.5.0"
